#!/usr/bin/env python3

"""Usage: hiritsu [-hvr] FILE

-h --help       show this
-v --verbose    show more info
-r --rename     rename file to include resolution and aspect ratio
"""

import os
from fractions import Fraction
from PIL import Image
from docopt import docopt


def get_aspect_ratio(width, height):
    """Calculate aspect ratio from width/height"""
    fraction = Fraction(width / height).limit_denominator()

    numerator = fraction.numerator
    denominator = fraction.denominator

    # Approximate/Change ratio for common standards.
    if (numerator == 64 and denominator == 27):
        numerator, denominator = 21, 9
    elif (numerator == 43 and denominator == 18):
        numerator, denominator = 21, 9
    elif (numerator == 8 and denominator == 5):
        numerator, denominator = 16, 10

    return f"{numerator}:{denominator}"


def get_image_info(file):
    """Returns a tuple of width, height and aspect ratio"""

    # Get the width and height of the image
    image = Image.open(file)
    width, height = image.size

    return (width, height, get_aspect_ratio(width, height))


def rename_file(file, width, height, aspect_ratio):
    filename, extension = os.path.splitext(file)
    image_info = f"({width}x{height}) [{aspect_ratio}]"

    os.rename(file, f"{filename} {image_info}{extension}")


if __name__ == "__main__":
    arguments = docopt(__doc__)

    width, height, aspect_ratio = get_image_info(arguments["FILE"])

    if (arguments["--verbose"]):
        print(f"Width: {width}")
        print(f"Height: {height}")
        print(f"Ratio: {aspect_ratio}")
    if (arguments["--rename"]):
        rename_file(arguments["FILE"], width, height, aspect_ratio)
    else:
        print(aspect_ratio)
